# Generated by Django 2.2.4 on 2019-08-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='mykid_no',
            field=models.CharField(default='xxx', max_length=20),
            preserve_default=False,
        ),
    ]
